/**
 * Async half of the PlantUML preview rendering: fetches each diagram SVG that
 * `fences.ts` emitted as an `<img>` and inlines it into the fragment.
 *
 * Why inline: the new PlantUML server (see the repo's `docs/important/
 * plantuml-server-salt-source-code.md`) embeds per-SALT-block source ranges
 * as `data-source-code` attributes on `<g>` elements *inside* the SVG. An
 * `<img>` hides the SVG's DOM, so cursor-sync highlighting and click-to-source
 * for those elements need the SVG tree reachable in the webview. Inlining also
 * keeps the existing fence-level `data-hmk-from`/`data-hmk-to` spans: they are
 * copied from the `<img>` onto the `<svg>` root.
 *
 * Fetching happens here (extension host, no CORS) rather than in the webview;
 * the SVG's own embedded `<script>` bundles are inert either way — scripts
 * inserted via `innerHTML` never execute, and the preview CSP would block
 * them regardless. A failed fetch keeps the original `<img>` (graceful
 * degradation: the diagram still renders as a plain image).
 *
 * Pure-ish: no `vscode` import and the network call is injectable, so the
 * replace logic is unit-testable in plain Node (`tests/plantuml_inline_check.cjs`).
 */

export interface SvgResponse {
	readonly ok: boolean;
	text(): Promise<string>;
}

export type SvgFetcher = (url: string, signal?: AbortSignal) => Promise<SvgResponse>;

const FETCH_TIMEOUT_MS = 8000;

const defaultFetcher: SvgFetcher = (url, signal) => fetch(url, { signal });

/** `<img … data-hmk-puml …>` — the tags generated by `fences.ts`. */
const PUML_IMG_REG = /<img\b([^>]*\bdata-hmk-puml\b[^>]*)>/gi;

/**
 * Replaces every PlantUML diagram `<img>` in `fragment` with the SVG fetched
 * from its `src`, preserving the fence-level source span. Non-puml tags and
 * any tag whose fetch fails are left untouched.
 */
export async function inlinePlantumlSvgs(fragment: string, fetcher: SvgFetcher = defaultFetcher): Promise<string> {
	const matches = Array.from(fragment.matchAll(PUML_IMG_REG));
	if (!matches.length) {
		return fragment;
	}
	const replacements = await Promise.all(matches.map(async (m) => {
		const attrs = parseAttrs(m[1]!);
		const src = attrs.get('src');
		if (!src) {
			return undefined;
		}
		try {
			const svg = await fetchSvg(src, fetcher);
			if (!svg) {
				return undefined;
			}
			return {
				start: m.index!,
				end: m.index! + m[0].length,
				html: buildInlineSvg(svg, attrs)
			};
		} catch {
			return undefined;
		}
	}));

	let out = '';
	let cursor = 0;
	for (const replacement of replacements) {
		if (!replacement) {
			continue;
		}
		out += fragment.slice(cursor, replacement.start) + replacement.html;
		cursor = replacement.end;
	}
	out += fragment.slice(cursor);
	return out;
}

async function fetchSvg(url: string, fetcher: SvgFetcher): Promise<string | undefined> {
	const controller = new AbortController();
	const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
	try {
		const response = await fetcher(url, controller.signal);
		if (!response.ok) {
			return undefined;
		}
		return extractSvg(await response.text());
	} finally {
		clearTimeout(timer);
	}
}

/** The `<svg …>…</svg>` root of a server response (skips the XML declaration). */
function extractSvg(text: string): string | undefined {
	const start = text.indexOf('<svg');
	const end = text.lastIndexOf('</svg>');
	if (start < 0 || end <= start) {
		return undefined;
	}
	return text.slice(start, end + 6);
}

/**
 * Copies the fence-level `data-hmk-from`/`data-hmk-to` spans onto the `<svg>`
 * root, and re-stamps `data-hmk-puml` so the marker matches both the inlined
 * SVG and the failed-fetch `<img>` code paths. Keeping the marker on the SVG
 * root gives a uniform `[data-hmk-puml]` hook for user stylesheets (e.g.
 * per-type invert); the default invert CSS does not select on it (PlantUML is
 * already covered by the `svg:not(.mermaid-wrapper *)` embedded-SVG fallback).
 *
 * `data-hmk-puml` is a boolean attribute on the source `<img>`, so `parseAttrs`
 * cannot read it — this function only ever runs on the puml-img path, so the
 * marker is stamped unconditionally.
 */
function buildInlineSvg(svg: string, attrs: Map<string, string>): string {
	let result = svg.replace(/^<svg\b/, '<svg data-hmk-puml=""');
	for (const key of ['data-hmk-from', 'data-hmk-to'] as const) {
		const value = attrs.get(key);
		if (value !== undefined) {
			result = result.replace(/^<svg\b/, `<svg ${key}="${value}"`);
		}
	}
	return result;
}

function parseAttrs(attrs: string): Map<string, string> {
	const map = new Map<string, string>();
	const reg = /([a-zA-Z][a-zA-Z0-9-]*)="([^"]*)"/g;
	let match: RegExpExecArray | null;
	while ((match = reg.exec(attrs))) {
		map.set(match[1].toLowerCase(), match[2]!);
	}
	return map;
}